fix NEUTRONRCF435AIO DFU INTERFAIRS BY UART1 UART3 AND I2C DELAY BUG
flightng/atbetaflight pull request #23
Opened 2022-12-28 13:30 UTC by shanggl

尝试修正2个bug:
* BUG1 : NEUTRONRCF435AIO 在串口 1、4 接elrs的情况下，长按Boot 按钮插usb线，受elrs干扰无法进入到usb dfu模式，无法进行固件升级
* BUG2 ：一定的情况下 NEUTRONRCF435AIO i2c 产生超过1800us的delay，怀疑与i2c异常错误有关，此delay导致炸机

解决方案：
* BUG1：通过增加 uart pin swap 特性，swap target uart1、uart4 TX\RX pin  （uart2 接了sbus 反相器不能修改，UART4 使用的是PC11 PC10 针脚），同时为了保持用户使用习惯，互换 uart5 TX/RX pin 

**注意：** 用户需要改变焊接习惯，ELRS 接收机TX 需要改为接 飞控 TX ，ELRS RX 改为接飞控RX

* BUG2 : I2C WAIT END time delay 缩短到原来的1/10 

结果：
BUG1 : 测试串口 1、4、5 焊接elrs 接收机正常通信， 能够正常进DFU 模式
BUG2:  NEUTRONRCF435AIO  默认DPS310 气压计功能正常，未出现delay情况

Entering CLI Mode, type 'exit' to return, or 'help'

# tasks
Task list             rate/hz  max/us  avg/us maxload avgload  total/ms   late    run reqd/us
00 - (         SYSTEM)     10      18       0    0.0%    0.0%         0      4   1014      12
01 - (         SYSTEM)    978      26       0    2.5%    0.0%        34    214  99311      16
**02 - (           GYRO)   3163      33       7   10.4%    2.2%      2287      0 321013       0**
03 - (         FILTER)   3163      50      22   15.8%    7.0%      7203      0 321013       0
04 - (            PID)   3163      64      37   20.2%   11.7%     12062      0 321013       0
05 - (            ACC)    791      10       1    0.7%    0.1%       135     47  80172       1
06 - (       ATTITUDE)    100      29       3    0.2%    0.0%        41      5  10125      23
07 - (             RX)    250      29       7    0.7%    0.1%       560     10  74469       9
08 - (         SERIAL)     99     154       0    1.5%    0.0%       155      0  10027     110
09 - (       DISPATCH)    974      25       0    2.4%    0.0%        44    133  99345      17
10 - (BATTERY_VOLTAGE)     50      21       1    0.1%    0.0%         5      9   5064      16
11 - (BATTERY_CURRENT)     50      18       0    0.0%    0.0%         1      5   5064       1
12 - ( BATTERY_ALERTS)      5       2       0    0.0%    0.0%         0      2    507       0
13 - (         BEEPER)     99      18       0    0.1%    0.0%         3      6  10027       1
16 - (           BARO)     37      45       6    0.1%    0.0%        68     12  12129      20
17 - (       ALTITUDE)     40      22       3    0.0%    0.0%        13      6   4053      20
19 - (      TELEMETRY)    491      35       0    1.7%    0.0%       115     33  49895      16
20 - (       LEDSTRIP)     99      60       1    0.5%    0.0%        12      1  10027      53
21 - (            OSD)     12     152      14    0.1%    0.0%       197     31  19874     123
23 - (            CMS)     20      24       2    0.0%    0.0%         1     10   2027      23
24 - (        VTXCTRL)      5      19       0    0.0%    0.0%         0      1    507      16
25 - (        CAMCTRL)      5      18       0    0.0%    0.0%         0      1    507      15
27 - (    ADCINTERNAL)      1      21       3    0.0%    0.0%         0      1    102      20
29 - (SPEED_NEGOTIATION)     99      18       0    0.1%    0.0%         4      4  10027       2
RX Check Function                  28       0                        80
Total (excluding SERIAL)                                21.1%

2022-12-28 13:49 UTC, DusKing1 requested changes
需要拆成两个PR

2022-12-28 13:49 UTC, DusKing1 commented on src/main/drivers/bus_i2c_atbsp.c
> +#define I2C_TIMEOUT                      0x870 //about 120 us at 288 mhz
现在大概是7us，注释是否需要对应修改一下？

2022-12-28 13:49 UTC, DusKing1 commented on src/main/drivers/bus_i2c_atbsp.c
> +//      i2c_wait_end(pHandle, I2C_TIMEOUT);
完全注释掉了是为什么

2022-12-30 12:19 UTC, shanggl commented
串口 1 也不能swap tx、rx pin， 数字图传插头已经固定线序，需要修改回去

2022-12-31 05:11 UTC, DusKing1 commented
> 串口 1 也不能swap tx、rx pin， 数字图传插头已经固定线序，需要修改回去

那就加以彻底拆成两个PR

2022-12-31 15:21 UTC, DusKing1 approved these changes
根据内部决议，本PR剥离涉及到target的修改，只保留driver层的改动

2022-12-31 15:22 UTC, merged