4.3.2 qfn48 target
flightng/atbetaflight pull request #24
Opened 2023-01-16 13:03 UTC by shanggl

增加 AT32F435CUG7  QFN48  target for NEUTRONRCF435MINI based on  the latest 4.3-bsp-rebase

2023-01-16 13:29 UTC, DusKing1 requested changes
见评论；缺少新目标的CI；commits合并为一个。

2023-01-16 13:29 UTC, DusKing1 commented on src/main/drivers/bus_i2c_atbsp_init.c
> +			I2CPINDEF(PH2,  GPIO_MUX_4),
缩进

2023-01-16 13:29 UTC, DusKing1 commented on src/main/drivers/bus_i2c_atbsp_init.c
> +			I2CPINDEF(PH3,GPIO_MUX_4),
缩进

2023-01-16 13:29 UTC, DusKing1 commented on src/main/io/displayport_crsf.c
> +    const uint8_t  truncLen = MIN((int)strlen(s), crsfScreen.cols-col);  // truncate at colCount
这个改动是必需的吗？

2023-01-16 13:29 UTC, DusKing1 commented on src/main/target/NEUTRONRCF435MINI/target.mk
> +#AT32F43xxMT7_TARGETS += $(TARGET)	#FOR 4032KB
多余

2023-01-16 14:49 UTC, shanggl commented on src/main/io/displayport_crsf.c
> +    const uint8_t  truncLen = MIN((int)strlen(s), crsfScreen.cols-col);  // truncate at colCount
是的，否则编译器会报错

2023-01-16 15:01 UTC, shanggl commented on src/main/target/NEUTRONRCF435MINI/target.mk
> +#AT32F43xxMT7_TARGETS += $(TARGET)	#FOR 4032KB
软串口作为备用方案

2023-01-29 16:38 UTC, DusKing1 commented
@shanggl 补充一下针对pin swap的具体修复

2023-01-31 14:18 UTC, DusKing1 approved these changes

2023-01-31 14:18 UTC, merged