Gf/dma/debug
flightng/atbetaflight pull request #55
Opened 2023-05-07 12:11 UTC by shanggl

1、优化SPI 实现，清理代码，去掉CCM检查
2、优化USB VCP 实现，删除定时器 
3、回退 esc-4-way 实现，去除中断屏蔽部分

优化SPI实现之后，更多实用DMA进行数据传输， 减少了系统中断，另外在 “万年入门” 的建议下删除usb的传输触发定时器， 进一步减少中断， 飞控电调通信部分无需再进行中断屏蔽。

2023-05-08 01:41 UTC, shanggl commented
测试之后， usb 偶发cli 回显比较慢的问题，可能偶发，需要进一步的验证。 

spi 、esc-4-way 已验证没问题

2023-05-08 09:46 UTC, DusKing1 requested changes
已完成实飞测试，没有明显问题。请查看审查

2023-05-08 09:46 UTC, DusKing1 commented on src/main/drivers/serial_usb_vcp_at32f43x.c
> +#endif
文件提示EOF，结尾需补一行

2023-05-08 09:46 UTC, DusKing1 commented on src/main/drivers/serial_usb_vcp_at32f43x.c
> +      tosend=APP_TX_BLOCK_SIZE;
缩进变更？

2023-05-08 09:46 UTC, DusKing1 commented on src/main/drivers/serial_usb_vcp_at32f43x.c
> +        break;
缩进变更？

2023-05-09 03:09 UTC, vangao-gg commented on src/main/drivers/bus_spi_at32bsp.c
>  void spiInitDevice(SPIDevice device)
IOConfigGPIOAF(IOGetByTag(spi->mosi), SPI_IO_AF_CFG, spi->mosiAF);中的SPI_IO_AF_CFG的GPIO_PULL_NONE设置是否需要改成GPIO_PULL_UP？

2023-05-09 06:54 UTC, shanggl commented on src/main/drivers/bus_spi_at32bsp.c
>  void spiInitDevice(SPIDevice device)
不需要修改

2023-05-10 23:58 UTC, DusKing1 approved these changes

2023-05-11 10:13 UTC, merged